---
- name: install curl, python, python venv, pip, django, nodejs, nginx, postgresql
  hosts: all
  become: true
  become_user: root
  gather_facts: true
  tasks:
   - name: Update and upgrade apt packages
     become: true
     apt:
       upgrade: yes
       update_cache: yes
       cache_valid_time: 86400 #One day
   - name: Install reqired packages
     apt: name={{ item }} state=present
     with_items:
       - git
       - curl
       - python3
       - python3-venv
       - python3-pip
       - nodejs
       - nginx
       - postgresql	
   - name: Install django version 3.0.0
     pip:
       name: django==3.0.0
